function [p,model] = pg_prepare_pengyue_tvms(p,fault,options)
%PG_PREPARE_PENGYUE_TVMS Build SP and PR physical TVMS lookups once.
% The returned parameter struct carries the immutable lookup into pg_tvms so
% the ODE/Newmark RHS never rebuilds tooth-section integrals.

arguments
    p struct
    fault struct
    options.GlobalScale (1,1) double {mustBePositive} = 1
    options.FoundationModel (1,1) string = "none"
    options.FoundationComplianceSun (1,1) double {mustBeNonnegative} = 0
    options.FoundationCompliancePlanet (1,1) double {mustBeNonnegative} = 0
    options.FoundationInnerRadiusSun (1,1) double = NaN
    options.FoundationInnerRadiusPlanet (1,1) double = NaN
    options.FoundationRootHalfAngleSun (1,1) double = NaN
    options.FoundationRootHalfAnglePlanet (1,1) double = NaN
    options.FoundationUfMode (1,1) string = "missing"
    options.LookupPoints (1,1) double {mustBeInteger,mustBeGreaterThan(options.LookupPoints,100)} = 801
    options.IntegrationPoints (1,1) double {mustBeInteger,mustBeGreaterThan(options.IntegrationPoints,200)} = 1200
end

if lower(strtrim(options.FoundationModel)) == "constant" || ...
        options.FoundationComplianceSun > 0 || options.FoundationCompliancePlanet > 0
    error('pg_prepare_pengyue_tvms:ConstantFoundationForbidden', ...
        'The temporary constant foundation compliance is disabled.');
end

if exist('pg_build_pengyue_sp_tvms_model','file') ~= 2
    error('pg_prepare_pengyue_tvms:MissingBuilder', ...
        ['Cannot find pg_build_pengyue_sp_tvms_model. Run setup_paths ' ...
         'from the repository root first.']);
end

model = pg_build_pengyue_sp_tvms_model(p,fault, ...
    'GlobalScale',options.GlobalScale, ...
    'FoundationModel',options.FoundationModel, ...
    'FoundationComplianceSun',options.FoundationComplianceSun, ...
    'FoundationCompliancePlanet',options.FoundationCompliancePlanet, ...
    'FoundationInnerRadiusSun',options.FoundationInnerRadiusSun, ...
    'FoundationInnerRadiusPlanet',options.FoundationInnerRadiusPlanet, ...
    'FoundationRootHalfAngleSun',options.FoundationRootHalfAngleSun, ...
    'FoundationRootHalfAnglePlanet',options.FoundationRootHalfAnglePlanet, ...
    'FoundationUfMode',options.FoundationUfMode, ...
    'LookupPoints',options.LookupPoints, ...
    'IntegrationPoints',options.IntegrationPoints);

% The PR lookup is built from the internal-mesh equations, not the legacy
% profileFloor/profileSin2 surrogate.  The ring-body foundation remains
% explicitly disabled because its rim geometry is missing from the source
% data; this is recorded in modelPr.ringFoundationStatus.
modelPr = pg_build_pengyue_pr_tvms_model(p,fault, ...
    'FoundationModel',options.FoundationModel, ...
    'LookupPoints',options.LookupPoints, ...
    'IntegrationPoints',options.IntegrationPoints);

p.mesh.tvmsSource = 'pengyue';
p.mesh.pengyueSpModel = model;
p.mesh.pengyuePrModel = modelPr;
p.mesh.pengyueTvmsMethod = struct('sunPlanet',model.method, ...
    'ringPlanet',modelPr.method);
end
